apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: usermanagement-ingress
  namespace: usermanagement

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - usermanagement.local
      secretName: usermanagement-tls

  rules:
    - host: usermanagement.local

      http:
        paths:
          - path: /api
            pathType: Prefix

            backend:
              service:
                name: backend
                port:
                  number: 80

          - path: /
            pathType: Prefix

            backend:
              service:
                name: frontend
                port:
                  number: 80