apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: usermanagement

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: swagnik10/usermanagement-backend:v1

          ports:
            - containerPort: 8080

          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: CONNECTION_STRING

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_KEY

            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_ISSUER

            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_AUDIENCE

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"