services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usermanagement-sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql
  db-init:
    build:
      context: ./SQL

    container_name: usermanagement-db-init

    environment:
      SA_PASSWORD: ${SA_PASSWORD}

    depends_on:
      - sqlserver

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: usermanagement-api

    depends_on:
      - db-init

    ports:
      - "5000:8080"

    environment:
      # ASPNETCORE_ENVIRONMENT: Development # Uncomment this line if you want to set the environment to Development for geeting the swagger UI

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

  frontend:
      build:
        context: ./Frontend
        dockerfile: Dockerfile

      container_name: usermanagement-frontend

      depends_on:
        - backend

      ports:
        - "3000:80"

volumes:
  sqlserver_data:
    name: usermanagement-sql-data