services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usermanagement-sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: usermanagement-api

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

    depends_on:
      - sqlserver

    restart: unless-stopped

volumes:
  sqlserver_data: