apiVersion: batch/v1
kind: Job

metadata:
  name: db-init
  namespace: usermanagement

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: db-init

          image: swagnik10/usermanagement-db-init:v1

          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SA_PASSWORD